# This is a basic workflow to help you get started with Actions

name: otherMethods

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    
    strategy:
      fail-fast: false
      matrix:
        project_folder_name: [apache_commons-weaver]
        
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - uses: actions/checkout@v2
      with:
        repository: matanhaz/Bench4BL
    - run: |
          pwd
          ls
        
