# This is a basic workflow to help you get started with Actions

name: Combined

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  steps_1-3_gathering_data:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    
    strategy:
      fail-fast: false
      matrix:
        project_folder_name: [apache_commons-weaver]
        
    outputs:
        output1: ${{matrix.project_folder_name}}
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: first
        run: sudo apt install build-essential
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: download packages
        run: |
              cd `git rev-parse --show-toplevel`
              pip install pipreqs
              pipreqs --ignore diagnoser,sfl_diagnoser .
              pip install -r requirements.txt
      
      # Runs a set of commands using the runners shell
      - name: Run
        run: |
              cd `git rev-parse --show-toplevel`
              python Run.py ${{matrix.project_folder_name}}
      # Runs a set of commands using the runners shell

      - name: Upload data
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: ${{matrix.project_folder_name}}
          # A file, directory or wildcard pattern that describes what to upload
          path: ./projects
          
          
  name2:
    needs: build
    runs-on: ubuntu-18.04
    
    strategy:
      fail-fast: false
      matrix:
        project_folder_name: [apache_commons-weaver]
        
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: first
        run: sudo apt install build-essential
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: download packages
        run: |
              cd `git rev-parse --show-toplevel`
              pip install pipreqs
              pipreqs --ignore diagnoser,sfl_diagnoser .
              pip install -r requirements.txt
      
      - name: create projects folder
        run: |
              cd `git rev-parse --show-toplevel`
              mkdir projects
              
      - name: Download result for job 1
        uses: actions/download-artifact@v2
        with:
          name: ${{needs.build.outputs.output1}}
          path: ./projects
          
      - name: Run
        run: |
              cd `git rev-parse --show-toplevel`
              python topicModeling.py ${{needs.build.outputs.output1}}
      # Runs a set of commands using the runners shell

      - name: Upload data
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: ${{needs.build.outputs.output1}}
          # A file, directory or wildcard pattern that describes what to upload
          path: ./projects
     

        
   # - name: Upload math result for job 2
   #   uses: actions/upload-artifact@v2
   #   with:
   #     name: homework
   #       path: ./math-homework.txt
